### ISSUE TITLE
Add Home View (improve)

### ISSUE THREAD

**Issue by MichaelKMalak** [MLH-Fellowship/zusammen#18]

**Comment by MichaelKMalak** [comment]
@diananova what do you suggest could be improved?

**Comment by diananova** [comment]
@MichaelKMalak I changed TeacherList.js in my recent pull request. Now the data that is fetched is from our API. I had to make a few adjustments, so now the homepage looks bad. If you could make it look presentable (like the way it was with the other API), that'd be cool.
